module.exports = {
  COOKIE: process.env.COOKIE,
  EMAIL: process.env.EMAIL,
  AUTHORIZATION_CODE: process.env.AUTHORIZATION_CODE,
  YIFENGCHUANHUA_CODE: process.env.YIFENGCHUANHUA_CODE,
  DINGDING_WEBHOOK: process.env.DINGDING_WEBHOOK,
  FEISHU_WEBHOOK: process.env.FEISHU_WEBHOOK,
}